server:
  port: 8080
spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:test
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  flyway:
    enabled: true
    url: jdbc:h2:mem:test
    user: sa
    password:
    schemas: INDITEX_ADMIN
    cleanOnValidationError: false
    locations: classpath:db
    baselineOnMigrate: true
    password-provider:
      enabled: false
